// You are developing a sales analytics system for a retail company. As part of the system, you need to implement a feature that sorts the sales data in descending order based on the revenue generated by each product. Write a program that prompts the user to enter the number of products and their respective revenue figures. The program should then use the insertion sort algorithm to sort the revenue figures in descending order and print with its iteration. After sorting, the program should display the products along with their corresponding sorted revenue figures. This feature will help the retail company identify its top-performing products and prioritize their sales efforts accordingly. It provides a clear view of the revenue generated by each product, aiding in strategic decision-making and optimizing sales performance within the company.

// Input Format

// The first line of input consists of N, representing the size of the array. The second line of input consists of the N array elements, separated by space.

// Constraints

// N > 0

// Output Format

// The first line of output prints the initial array of elements, separated by space. The following lines print the result of each iteration. The last line of output prints the final sorted array in decreasing order.

// Sample Input 0

// 4
// 471 774 814 136
// Sample Output 0

// Initial order: 471 774 814 136 
// After Iteration 1: 774 471 814 136 
// After Iteration 2: 814 774 471 136 
// After Iteration 3: 814 774 471 136 
// Sorted order: 814 774 471 136
// Sample Input 1

// 3
// 82 45 29
// Sample Output 1

// Initial order: 82 45 29 
// After Iteration 1: 82 45 29 
// After Iteration 2: 82 45 29 
// Sorted order: 82 45 29

#include<iostream>
using namespace std;

void displayArray(const int arr[], int size) {
    for (int i = 0; i < size; i++) {
        cout << arr[i] << " ";
    }
    cout << endl;
}
void insertionSort(int arr[], int size) {
    for (int i = 1; i < size; i++) {
        int key = arr[i];
        int j = i - 1;

        while (j >= 0 && arr[j] < key) {
            arr[j + 1] = arr[j];
            j = j - 1;
        }

        arr[j + 1] = key;
        cout << "After Iteration " << i << ": ";
        displayArray(arr, size);
    }
}

int main() {
    int n;
    cin >> n;
    int revenue[n];
    for (int i = 0; i < n; i++) {
        cin >> revenue[i];
    }

cout << "Initial order: ";
displayArray(revenue, n);
insertionSort(revenue, n);

    cout << "Sorted order: ";
    displayArray(revenue, n);

    return 0;
}
